### ISSUE TITLE
Hello, can you share the data set

### ISSUE THREAD

**Issue by yyaoshuai** [rulixiang/CorrFusionNet#14]

**Comment by rulixiang** [comment]
Hey! @yyaoshuai , for dataset request, please visit this [URL](http://sigma.whu.edu.cn/newspage.php?q=2021_06_27 ), or contact chen.wu@whu.edu.cn.

**Comment by yyaoshuai** [comment]
Hello, the web link of the data set is open for news and there is no link to download the data set
